trigger:
  - feature

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformDeploy
    displayName: 'Terraform Stage'
    jobs:
      - job: TerraformJob
        displayName: 'Terraform Init Plan Apply'
        steps:
          - task: Bash@3
            displayName: 'Install Terraform'
            inputs:
              targetType: 'inline'
              script: |
                echo "Installing Terraform..."
                curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
                unzip terraform.zip
                sudo mv terraform /usr/local/bin/
                terraform -version

          - task: TerraformTaskV5@5
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'arif-service connection'
              backendAzureRmStorageAccountName: 'arifstorage12345'
              backendAzureRmContainerName: 'arif-container'
              backendAzureRmKey: 'terraform.tfstate1'
              backendAzureRmUseEntraIdForAuthentication: false

          - task: TerraformTask@5
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'arif-service connection'

          - task: TerraformTask@5
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'arif-service connection'
              args: '-auto-approve'
