trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: TerraformDeploy
    displayName: 'Terraform via Bash'
    jobs:
      - job: TerraformJob
        displayName: 'Run Terraform Commands'
        steps:
          - task: AzureCLI@2
            displayName: 'Terraform Init, Plan, Apply'
            inputs:
              azureSubscription: 'arif-service connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              workingDirectory: '$(System.DefaultWorkingDirectory)'
              inlineScript: |
                # Install Terraform
                echo "Installing Terraform"
                curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
                unzip terraform.zip
                sudo mv terraform /usr/local/bin/
                terraform -version

                # Init
                terraform init \
                  -backend-config="resource_group_name=your-backend-rg" \
                  -backend-config="storage_account_name=arifstorage12345" \
                  -backend-config="container_name=arif-container" \
                  -backend-config="key=terraform.tfstate1"

                # Plan
                terraform plan -var-file="terraform.tfvars"

                # Apply
                terraform apply -auto-approve -var-file="terraform.tfvars"
